@url = http://localhost:9999/api/v1/roles

### CREATE PERMISSION
POST {{url}}
Content-Type: application/json

{
  "name": "Adminstrator",
  "desc": "Quản trị viên",
  "permissions": [11, 12, 1, 5]
}


### UPDATE PERMISSION
PATCH {{url}}/1
Content-Type: application/json

{
  "name": "Add Product And Post",
  "desc": "Thêm sản phẩm và bài viết",
  "permissions": [1, 11]
}

### DELETE PERMISSION
DELETE  {{url}}/6

### GET ALL PERMISSION
GET {{url}}?page=1&limit=5

### GET BY ID
GET {{url}}/1